/* DROPS
CREATE DATABASE ITSC_DB_V3;
DROP TABLE SEDES;
DROP TABLE CARRERAS;
DROP TABLE SEDECARRERA;
DROP TABLE ALUMNOS;
DROP TABLE DOCENTES;
DROP TABLE PRECEPTORES;
DROP TABLE MATERIAS;
DROP TABLE MATERIACARRERA;
DROP TABLE HORARIOS;
DROP TABLE CLASES;
DROP TABLE ASISTENCIAS;
DROP TABLE INSCRIPCIONES;
DROP TABLE PAGOS;
DROP TABLE CURSANTES;
DROP TABLE EXAMENES;
DROP TABLE NOTAS;
*/

CREATE TABLE SEDES (
SEDE_ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION NVARCHAR(100),
TELEFONO NVARCHAR(50),
EMAIL NVARCHAR(100),
DIRECCION NVARCHAR(100),
PISO INT,
DEPTO NVARCHAR(10),
BARRIO NVARCHAR(100),
LOCALIDAD NVARCHAR(100),
HORA_DESDE NVARCHAR(10),
HORA_HASTA NVARCHAR(10),
DIA_DESDE NVARCHAR(10),
DIA_HASTA NVARCHAR(10),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE()

);

CREATE TABLE CARRERAS (
CARRERA_ID INT IDENTITY(1,1) PRIMARY KEY, 
DESCRIPCION NVARCHAR(100),
PLAN_CARRERA NVARCHAR(50),
PLAN_START_DATE DATE,
PLAN_END_DATE DATE DEFAULT NULL,

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE SEDECARRERA (
SEDECARRERA_ID INT IDENTITY(1,1) PRIMARY KEY, 
CARRERA_ID INT FOREIGN KEY REFERENCES CARRERAS(CARRERA_ID) ON DELETE SET NULL, 
SEDE_ID INT FOREIGN KEY REFERENCES SEDES(SEDE_ID) ON DELETE SET NULL,
TURNO NVARCHAR(10),
CODIGO_CARRERA NVARCHAR(10), --consultar

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE ALUMNOS (
ALUMNO_ID INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE NVARCHAR(50), 
APELLIDO NVARCHAR(50),
FECHA_NACIMIENTO DATE,
DNI NVARCHAR(15),
PASSWORD NVARCHAR(100),
TELEFONO NVARCHAR(50),
EMAIL NVARCHAR(100),
DIRECCION NVARCHAR(100),
PISO INT,
DEPTO NVARCHAR(10),
BARRIO NVARCHAR(50),
LOCALIDAD NVARCHAR(100),
CONTACTO_EMERGENCIA NVARCHAR(100),
CONTACTO_EMERGENCIA_TEL NVARCHAR(50),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE()
);

CREATE TABLE DOCENTES (
DOCENTE_ID INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE NVARCHAR(100),
APELLIDO NVARCHAR(100),
FECHA_NACIMIENTO DATE,
DNI NVARCHAR(20),
PASSWORD NVARCHAR(100),
TELEFONO NVARCHAR(100),
EMAIL NVARCHAR(100),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE PRECEPTORES (
PRECEPTOR_ID INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE NVARCHAR(100),
APELLIDO NVARCHAR(100),
FECHA_NACIMIENTO DATE,
DNI NVARCHAR(20),
PASSWORD NVARCHAR(100),
TELEFONO NVARCHAR(100),
EMAIL NVARCHAR(100),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE MATERIAS (
MATERIA_ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION NVARCHAR(100),
COD_RESOLUCION NVARCHAR(10),
CARRERA_ANIO INT, -- CHEQUEAR ESTO. Acá iría el año de la carrera en el que se dicta la materia, para poder filtrar por año.

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE MATERIACARRERA (
MATERIACARRERA_ID INT IDENTITY(1,1) PRIMARY KEY,
MATERIA_ID INT FOREIGN KEY REFERENCES MATERIAS(MATERIA_ID) ON DELETE SET NULL,
SEDECARRERA_ID INT FOREIGN KEY REFERENCES SEDECARRERA(SEDECARRERA_ID) ON DELETE SET NULL,
DOCENTE_ID INT FOREIGN KEY REFERENCES DOCENTES(DOCENTE_ID) ON DELETE SET NULL,
PRECEPTOR_ID INT FOREIGN KEY REFERENCES PRECEPTORES(PRECEPTOR_ID) ON DELETE SET NULL,
CICLO_LECTIVO INT,
CURSO NVARCHAR(10),       --CHEQUEAR ESTO. ACÁ IRIA ALGO COMO A,B,C o1A, 2A etc.
REGULARIZABLE INT,

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE HORARIOS (
HORARIO_ID INT IDENTITY(1,1) PRIMARY KEY,
MATERIACARRERA_ID INT FOREIGN KEY REFERENCES MATERIACARRERA(MATERIACARRERA_ID) ON DELETE SET NULL,
HORA_INICIO NVARCHAR(20),
HORA_FIN NVARCHAR(20),
DIA NVARCHAR(20),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE CLASES (
CLASE_ID INT IDENTITY(1,1) PRIMARY KEY,
MATERIACARRERA_ID INT FOREIGN KEY REFERENCES MATERIACARRERA(MATERIACARRERA_ID) ON DELETE SET NULL,
FECHA DATE,
DESCRIPCION NVARCHAR(200),
OBSERVACIONES NVARCHAR(200),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE CURSANTES (
CURSANTE_ID INT IDENTITY(1,1) PRIMARY KEY,
ALUMNO_ID INT FOREIGN KEY REFERENCES ALUMNOS(ALUMNO_ID) ON DELETE SET NULL,
MATERIACARRERA_ID INT FOREIGN KEY REFERENCES MATERIACARRERA(MATERIACARRERA_ID) ON DELETE SET NULL,
ESTADO_CURSADA NVARCHAR(20),
REGULARIDAD_END_DATE DATE,
OBSERVACIONES NVARCHAR(200),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE ASISTENCIAS (
ASISTENCIA_ID INT IDENTITY(1,1) PRIMARY KEY,
CLASE_ID INT FOREIGN KEY REFERENCES CLASES(CLASE_ID) ON DELETE SET NULL,
--ALUMNO_ID INT FOREIGN KEY REFERENCES ALUMNOS(ALUMNO_ID), 		--CONSULTAR. O CURSANTE_ID??
CURSANTE_ID INT FOREIGN KEY REFERENCES CURSANTES(CURSANTE_ID) ON DELETE SET NULL,
ASISTENCIA INT, 
JUSTIFICADO INT,
OBSERVACIONES NVARCHAR(200),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE INSCRIPCIONES (
INSCRIPCION_ID INT IDENTITY(1,1) PRIMARY KEY,
ALUMNO_ID INT FOREIGN KEY REFERENCES ALUMNOS(ALUMNO_ID) ON DELETE SET NULL,
SEDECARRERA_ID INT FOREIGN KEY REFERENCES SEDECARRERA(SEDECARRERA_ID) ON DELETE SET NULL,
FOTOCOPIA_DOC_X2 INT DEFAULT 0,
FOTOCOPIA_TITULO INT DEFAULT 0,
FOTOCOPIA_ANALITICO INT DEFAULT 0,
EXAMEN_NIVELATORIO INT DEFAULT 0,
COOPERADORA_TOTAL FLOAT,
COOPERADORA_ESTADO NVARCHAR(20),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE PAGOS (
PAGO_ID INT IDENTITY(1,1) PRIMARY KEY,
INSCRIPCION_ID INT FOREIGN KEY REFERENCES INSCRIPCIONES(INSCRIPCION_ID) ON DELETE SET NULL,
FECHA DATE, 
MONTO FLOAT,
SALDO FLOAT,

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);


CREATE TABLE EXAMENES (
EXAMEN_ID INT IDENTITY(1,1) PRIMARY KEY,
MATERIACARRERA_ID INT FOREIGN KEY REFERENCES MATERIACARRERA(MATERIACARRERA_ID) ON DELETE SET NULL,
FECHA DATE,
DESCRIPCION NVARCHAR(100),
ETAPA INT,
TIPO NVARCHAR(100),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);

CREATE TABLE NOTAS (
NOTA_ID INT IDENTITY(1,1) PRIMARY KEY,
EXAMEN_ID INT FOREIGN KEY REFERENCES EXAMENES(EXAMEN_ID) ON DELETE SET NULL,
--ALUMNO_ID INT FOREIGN KEY REFERENCES ALUMNOS(ALUMNO_ID), 
CURSANTE_ID INT FOREIGN KEY REFERENCES CURSANTES(CURSANTE_ID) ON DELETE SET NULL,
NOTA FLOAT,
OBSERVACIONES NVARCHAR(200),

STATUS INT DEFAULT 1,
ADD_DATE DATETIME DEFAULT GETDATE(),
LAST_UPDATED_DATE DATETIME DEFAULT GETDATE() 
);
